# Generated by Django 5.2.14 on 2026-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(verbose_name='Проект')),
                ('region_description', models.TextField(verbose_name='Описание региона')),
                ('first_club', models.TextField(verbose_name='Клуб первых')),
                ('book_territory', models.TextField(verbose_name='Территория книги и чтения')),
                ('most_reading_region', models.TextField(verbose_name='Самый читающий регион')),
                ('region_url', models.URLField(verbose_name='Урл региона')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_description', models.TextField(verbose_name='Дескрипшен СЕО')),
                ('right_column_text', models.TextField(verbose_name='Текстовое поле для вставки в любое место (пока предварительно правая колонка в регионе)')),
            ],
        ),
    ]
