# Generated by Django 5.2.14 on 2026-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_project', models.TextField(verbose_name='Главный проект')),
                ('contest_description', models.TextField(verbose_name='Описание конкурса')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_descriptor', models.TextField(verbose_name='Дескриптор СЕО')),
                ('regions', models.ManyToManyField(to='Site.region', verbose_name='Регион')),
            ],
        ),
    ]
