# Generated by Django 5.2.14 on 2026-05-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_bookterritory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='right_column_text',
            field=models.TextField(verbose_name='Текстовое поле для вставки в любое место'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField(verbose_name='Описание проекта')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2026, verbose_name='Год')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_descriptor', models.TextField(verbose_name='Дескриптор СЕО')),
                ('internal_tag', models.CharField(max_length=255, verbose_name='Тег для внутренней фильтрации в админке')),
                ('slider', models.BooleanField(default=False, verbose_name='Слайдер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Снятие с активации / активация')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Site.region', verbose_name='Регион')),
            ],
        ),
    ]
