# Generated by Django 5.2.14 on 2026-05-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_region_right_column_text_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='book_territory',
        ),
        migrations.RemoveField(
            model_name='region',
            name='first_club',
        ),
        migrations.RemoveField(
            model_name='region',
            name='project',
        ),
    ]
