# Generated by Django 5.2.14 on 2026-05-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_remove_region_book_territory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookterritory',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='club',
            name='regions',
        ),
    ]
