# Generated by Django 5.2.14 on 2026-05-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_remove_bookterritory_regions_remove_club_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionBookTerritoryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('book_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.bookterritory')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.region')),
            ],
            options={
                'unique_together': {('region', 'book_territory', 'year')},
            },
        ),
        migrations.AddField(
            model_name='bookterritory',
            name='regions',
            field=models.ManyToManyField(through='Site.RegionBookTerritoryMembership', to='Site.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='RegionClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.club')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.region')),
            ],
            options={
                'unique_together': {('region', 'club', 'year')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='regions',
            field=models.ManyToManyField(through='Site.RegionClubMembership', to='Site.region', verbose_name='Регион'),
        ),
    ]
