# Generated by Django 5.2.14 on 2026-05-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_regionbookterritorymembership_bookterritory_regions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.TextField(verbose_name='HTML код')),
                ('tag_for_insertion', models.CharField(max_length=255, verbose_name='Тег для вставки')),
                ('internal_tag', models.CharField(max_length=255, verbose_name='Тег для внутренней фильтрации')),
            ],
            options={
                'verbose_name': 'HTML сниппет',
                'verbose_name_plural': 'HTML сниппеты',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='bookterritory',
            options={'verbose_name': 'Территория книги', 'verbose_name_plural': 'Территория книги'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб первых', 'verbose_name_plural': 'Клубы первых'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='regionclubmembership',
            options={'verbose_name': 'Членство в клубе первых', 'verbose_name_plural': 'Членства в клубах первых'},
        ),
        migrations.AlterUniqueTogether(
            name='regionbookterritorymembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='slider',
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название слайдера')),
                ('internal_tag', models.CharField(max_length=255, verbose_name='Тег для внутренней фильтрации')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Site.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.photo')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.slider')),
            ],
            options={
                'verbose_name': 'Фото в слайдере',
                'verbose_name_plural': 'Фото в слайдерах',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='slider',
            name='photos',
            field=models.ManyToManyField(through='Site.SliderPhoto', to='Site.photo', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='slider',
            name='tag_for_insertion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.tag', verbose_name='Тег для вставки'),
        ),
    ]
