# Generated by Django 5.2.14 on 2026-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_htmlsnippet_photo_tag_alter_bookterritory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlsnippet',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='htmlsnippet',
            name='tag_for_insertion',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Тег для вставки'),
        ),
    ]
