# Generated by Django 5.2.14 on 2026-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_htmlsnippet_name_alter_htmlsnippet_tag_for_insertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlsnippet',
            name='tag_for_insertion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тег для вставки'),
        ),
    ]
