# Generated by Django 5.2.14 on 2026-05-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_alter_htmlsnippet_tag_for_insertion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlsnippet',
            name='tag_for_insertion',
        ),
    ]
