# Generated by Django 5.2.14 on 2026-05-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_remove_htmlsnippet_tag_for_insertion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='tag_for_insertion',
        ),
        migrations.AlterField(
            model_name='slider',
            name='internal_tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тег для внутренней фильтрации'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.project', verbose_name='Проект'),
        ),
    ]
