# Generated by Django 5.2.14 on 2026-05-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_remove_slider_tag_for_insertion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionbookterritorymembership',
            options={'verbose_name': 'Участие региона в территории книги', 'verbose_name_plural': 'Участия регионов в территориях книги'},
        ),
    ]
