# Generated by Django 5.2.14 on 2026-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_alter_regionbookterritorymembership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionbookterritorymembership',
            options={'verbose_name': 'Членство в территории книги', 'verbose_name_plural': 'Членство в территориях книги'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
