# Generated by Django 5.2.14 on 2026-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_alter_regionbookterritorymembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='html_code',
            field=models.TextField(blank=True, help_text='HTML, который будет выводиться при использовании тега.', verbose_name='HTML код'),
        ),
    ]
