# Generated by Django 5.2.14 on 2026-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0015_tag_html_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
