# Generated by Django 5.2.14 on 2026-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_url',
            field=models.URLField(blank=True, help_text='Если оставить пустым, будет сформирован из тайтла', verbose_name='Урл региона'),
        ),
    ]
