# Generated by Django 5.2.14 on 2026-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_region_title_alter_region_region_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_descriptor', models.TextField(verbose_name='Дескриптор СЕО')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('category', models.CharField(choices=[('news', 'Новость'), ('most_reading_region', 'СЧР (самый читающий регион)')], default='news', max_length=30, verbose_name='Тип')),
                ('image_16x10', models.ImageField(upload_to='news/16x10/%Y/%m/%d/', verbose_name='Картинка 16:10')),
                ('image_1x1', models.ImageField(upload_to='news/1x1/%Y/%m/%d/', verbose_name='Картинка 1:1')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
