# Generated by Django 5.2.14 on 2026-05-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Снятие с активации / активация')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
        migrations.CreateModel(
            name='StaticPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_16x10', models.ImageField(upload_to='static_pages/16x10/%Y/%m/%d/', verbose_name='Картинка 16 к 10')),
                ('image_1x1', models.ImageField(upload_to='static_pages/1x1/%Y/%m/%d/', verbose_name='Картинка 1 к 1')),
                ('static_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Site.staticpage')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='StaticPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_descriptor', models.TextField(verbose_name='Дескриптор СЕО')),
                ('static_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='Site.staticpage')),
            ],
            options={
                'verbose_name': 'СЕО',
                'verbose_name_plural': 'СЕО',
            },
        ),
    ]
