# Generated by Django 5.2.14 on 2026-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_staticpage_staticpageimage_staticpageseo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpageseo',
            name='static_page',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image_16x10',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages/16x10/%Y/%m/%d/', verbose_name='Картинка 16 к 10'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image_1x1',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages/1x1/%Y/%m/%d/', verbose_name='Картинка 1 к 1'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='seo_descriptor',
            field=models.TextField(blank=True, null=True, verbose_name='Дескриптор СЕО'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайтл СЕО'),
        ),
        migrations.DeleteModel(
            name='StaticPageImage',
        ),
        migrations.DeleteModel(
            name='StaticPageSeo',
        ),
    ]
