# Generated by Django 5.2.14 on 2026-05-27 11:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0020_remove_staticpageseo_static_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookterritory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='htmlsnippet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='regionbookterritorymembership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='regionclubmembership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='bookterritory',
            name='contest_description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание конкурса'),
        ),
        migrations.AlterField(
            model_name='club',
            name='contest_description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание конкурса'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='region',
            name='most_reading_region',
            field=ckeditor.fields.RichTextField(verbose_name='Самый читающий регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_url',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет сформирован из тайтла', max_length=255, verbose_name='Урл региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='right_column_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовое поле для вставки в любое место'),
        ),
        migrations.AlterField(
            model_name='region',
            name='seo_description',
            field=models.TextField(verbose_name='Дескришен СЕО'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
