# Generated by Django 5.2.14 on 2026-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_bookterritory_is_active_club_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='html_code',
            field=models.TextField(blank=True, null=True, verbose_name='HTML код'),
        ),
    ]
