# Generated by Django 5.2.14 on 2026-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_slider_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='regenerate_html',
            field=models.BooleanField(default=False, verbose_name='Пересоздать HTML-код при сохранении'),
        ),
    ]
