# Generated by Django 5.2.14 on 2026-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0023_slider_regenerate_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coat_of_arms',
            field=models.ImageField(blank=True, null=True, upload_to='regions/coats_of_arms/', verbose_name='Герб'),
        ),
        migrations.AlterField(
            model_name='region',
            name='most_reading_region',
            field=models.TextField(verbose_name='Самый читающий регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='right_column_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое поле для вставки в любое место'),
        ),
    ]
