# Generated by Django 5.2.14 on 2026-05-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0024_region_coat_of_arms_alter_region_most_reading_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Тайтл СЕО')),
                ('seo_descriptor', models.TextField(verbose_name='Дескриптор СЕО')),
                ('main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_main_project', to='Site.region', verbose_name='Главный проект')),
                ('short_list', models.ManyToManyField(related_name='contest_short_list', to='Site.region', verbose_name='Шорт лист')),
                ('top', models.ManyToManyField(related_name='contest_top', to='Site.region', verbose_name='Топ')),
            ],
            options={
                'verbose_name': 'Конкурс (итоги)',
                'verbose_name_plural': 'Конкурсы (итоги)',
                'unique_together': {('main_project', 'year')},
            },
        ),
    ]
