# Generated by Django 5.2.14 on 2026-05-27 15:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0025_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полный текст'),
        ),
    ]
