# Generated by Django 5.2.14 on 2026-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0026_contest_full_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='html_code',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='regenerate_html',
        ),
    ]
