# Generated by Django 5.2.14 on 2026-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_remove_slider_html_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='svg_id',
            field=models.CharField(blank=True, help_text='Идентификатор региона в SVG-карте (например, PETERSBURG, VORONEZH)', max_length=100, null=True, unique=True, verbose_name='ID на карте (SVG ID)'),
        ),
    ]
