# Generated by Django 5.2.14 on 2026-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0028_region_svg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='svg_id',
            field=models.CharField(blank=True, choices=[('PETERSBURG', 'Санкт-Петербург'), ('ARHANGELSKAYA_OBLAST', 'Архангельская область'), ('BELGOROD', 'Белгородская область'), ('VORONEZH', 'Воронежская область'), ('ULYANOVSK', 'Ульяновская область'), ('NOVOSIBIRSKAYA_OBLAST', 'Новосибирская область'), ('IRKUTSK', 'Иркутская область'), ('TATARSTAN', 'Республика Татарстан'), ('YAKUTIYA', 'Республика Саха (Якутия)'), ('RESPUBLIKA_BASHKORTOSTAN', 'Республика Башкортостан'), ('KURSKAYA_OBLAST', 'Курская область')], help_text='Выберите идентификатор региона для отображения на интерактивной SVG-карте', max_length=100, null=True, unique=True, verbose_name='ID на карте (SVG ID)'),
        ),
    ]
