# Generated by Django 5.2.14 on 2026-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0029_alter_region_svg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='svg_id',
            field=models.CharField(blank=True, help_text='Идентификатор региона в SVG-карте (например, PETERSBURG, VORONEZH)', max_length=100, null=True, unique=True, verbose_name='ID на карте (SVG ID)'),
        ),
    ]
