# Generated by Django 5.2.14 on 2026-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0030_alter_region_svg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_16x10',
            field=models.ImageField(blank=True, null=True, upload_to='news/16x10/%Y/%m/%d/', verbose_name='Картинка 16:10'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_1x1',
            field=models.ImageField(blank=True, null=True, upload_to='news/1x1/%Y/%m/%d/', verbose_name='Картинка 1:1'),
        ),
    ]
