# Generated by Django 5.2.14 on 2026-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0031_alter_news_image_16x10_alter_news_image_1x1'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='ЧПУ (Slug)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'Новость'), ('most_reading_region', 'СЧР (самый читающий регион)'), ('forum-fest', 'Фестиваль форум')], default='news', max_length=30, verbose_name='Тип'),
        ),
    ]
