# Generated by Django 5.2.14 on 2026-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0032_news_slug_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='ЧПУ (Slug)'),
        ),
    ]
