# Generated by Django 5.2.14 on 2026-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0033_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Документ новости',
                'verbose_name_plural': 'Документы новостей',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='documents',
            field=models.ManyToManyField(blank=True, to='Site.newsdocument', verbose_name='Документы'),
        ),
    ]
