# Generated by Django 5.2.14 on 2026-06-10 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0034_newsdocument_news_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='files/')),
                ('icon', models.CharField(choices=[('pdf.png', 'PDF'), ('doc.png', 'DOC'), ('xls.png', 'Excel'), ('zip.png', 'Архив'), ('img.png', 'Изображение'), ('default.png', 'По умолчанию')], default='default.png', max_length=100, verbose_name='Иконка')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('show_on_page', models.BooleanField(default=False, verbose_name='Выводить на странице файлов')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.DeleteModel(
            name='NewsDocument',
        ),
        migrations.AlterField(
            model_name='news',
            name='documents',
            field=models.ManyToManyField(blank=True, to='Site.file', verbose_name='Документы'),
        ),
    ]
