# Generated by Django 5.2.14 on 2026-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0035_file_delete_newsdocument_alter_news_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlsnippet',
            name='category',
            field=models.CharField(choices=[('custom_tag', 'Кастомный тег'), ('festival', 'Фестиваль'), ('interview', 'Интервью'), ('intensive', 'Образовательный интенсив')], default='custom_tag', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='htmlsnippet',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Тайтл'),
        ),
    ]
