# Generated by Django 5.2.14 on 2026-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0036_htmlsnippet_category_alter_htmlsnippet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlsnippet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='htmlsnippet',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название (для тега)'),
        ),
    ]
