# Generated by Django 5.2.14 on 2026-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0038_speaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
