# Generated by Django 5.2.14 on 2026-06-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0039_delete_speaker_alter_news_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='default_slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_regions', to='Site.slider', verbose_name='Дефолтный слайдер'),
        ),
        migrations.AddField(
            model_name='region',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='regions/main_photos/', verbose_name='Главное фото региона'),
        ),
    ]
