# Generated by Django 5.2.14 on 2026-06-17 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0041_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionclubmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regionclubmembership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='regionclubmembership',
            name='region',
        ),
        migrations.RemoveField(
            model_name='bookterritory',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='club',
            name='regions',
        ),
        migrations.AlterModelOptions(
            name='bookterritory',
            options={'verbose_name': 'Территория книги и чтения', 'verbose_name_plural': 'Территория книги и чтения'},
        ),
        migrations.RemoveField(
            model_name='bookterritory',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='bookterritory',
            name='main_project',
        ),
        migrations.RemoveField(
            model_name='bookterritory',
            name='seo_descriptor',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='club',
            name='main_project',
        ),
        migrations.RemoveField(
            model_name='club',
            name='seo_descriptor',
        ),
        migrations.AddField(
            model_name='bookterritory',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='Дескриптор СЕО'),
        ),
        migrations.AddField(
            model_name='bookterritory',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текстовое поле'),
        ),
        migrations.AddField(
            model_name='club',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='Дескриптор СЕО'),
        ),
        migrations.AddField(
            model_name='club',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текстовое поле'),
        ),
        migrations.AddField(
            model_name='bookterritory',
            name='regions',
            field=models.ManyToManyField(blank=True, to='Site.region', verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='bookterritory',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тайтл СЕО'),
        ),
        migrations.AddField(
            model_name='club',
            name='regions',
            field=models.ManyToManyField(blank=True, to='Site.region', verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='club',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тайтл СЕО'),
        ),
        migrations.DeleteModel(
            name='RegionBookTerritoryMembership',
        ),
        migrations.DeleteModel(
            name='RegionClubMembership',
        ),
    ]
