# Generated by Django 5.2.14 on 2026-06-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0042_alter_regionclubmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='laureates',
            field=models.TextField(blank=True, null=True, verbose_name='Лауреаты'),
        ),
    ]
