# Generated by Django 5.2.14 on 2026-06-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0043_region_laureates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTerritoryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('book_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.bookterritory')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.region')),
            ],
            options={
                'verbose_name': 'Регион в территории книги',
                'verbose_name_plural': 'Регионы в территории книги',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='bookterritory',
            name='regions',
        ),
        migrations.AddField(
            model_name='bookterritory',
            name='regions',
            field=models.ManyToManyField(blank=True, through='Site.BookTerritoryRegion', to='Site.region', verbose_name='Регионы'),
        ),
        migrations.CreateModel(
            name='ClubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.club')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.region')),
            ],
            options={
                'verbose_name': 'Регион в клубе',
                'verbose_name_plural': 'Регионы в клубе',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='club',
            name='regions',
        ),
        migrations.AddField(
            model_name='club',
            name='regions',
            field=models.ManyToManyField(blank=True, through='Site.ClubRegion', to='Site.region', verbose_name='Регионы'),
        ),
    ]
